apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: parasol-insurance-entities
  description: Shared Parasol Insurance catalog entities
spec:
  targets:
    - ./system.yaml
    - ./system-secured.yaml
    - ./resources.yaml
    - ./llm-inference-server/resource.yaml
